### ISSUE TITLE
Build fails in F-Droid

### ISSUE THREAD

**Issue by mvmike** [mvmike/min-cal-widget#100]
After moving the app to JDK-17 in 6efb42f once it became stable, F-Droid build fails since it's configured to do so with JDK-11

PR has been opened in fdroiddata to fix it, although I'm unsure if this is the correct way to do so:

* https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11147

@linsui, since you helped with the migration to JDK-11 in https://github.com/mvmike/min-cal-widget/issues/66, would you mind assisting (or point me in the right direction) me here? Haven't found any info in the documentation about how to tackle this.

**Comment by linsui** [comment]
Currently it's impossible because we are still on Debian Stretch and Jave 17 is not packaged. We're going to upgrade to Debain Bulleye. See https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10909.

**Comment by mvmike** [comment]
Thanks for the heads up, will watch the PR and try again once it's merged, thanks

**Comment by mvmike** [comment]
Reopened since build server has been upgraded to latest debian

**Comment by mvmike** [comment]
Build passed in f-droid and new version is available, thanks for the assistance @linsui 😃 


![Screenshot at 2022-10-18 15-47-21](https://user-images.githubusercontent.com/20406251/196448383-c073dedc-3ab9-4662-b2c3-b5b0fe9cbecb.png)
