### ISSUE TITLE
Calendar events are not visible as symbols

### ISSUE THREAD

**Issue by S-Sajith** [mvmike/min-cal-widget#122]
So I was experimenting with a couple of different calendar apps and then after I unistalled one of them the event symbols on mincal widget stopped showing , I have tried uninstalling the app and reinstalling , rebooting , uninstalling and reinstalling the calendar apps but the issue persists. Plesse suggest a fix
![Screenshot_20220929-235108](https://user-images.githubusercontent.com/88919814/193112693-1910f6ee-a756-473f-b881-caade180d036.png)
![Screenshot_20220929-235123](https://user-images.githubusercontent.com/88919814/193112707-1c259079-07e1-48a4-82ca-2b26e8b63648.png)

**Comment by mvmike** [comment]
Mincal queries the system for visible calendar events, if they're visible in the calendar app they should appear in the widget too. Could you confirm this is the case?

On the other hand, sometimes wiping the data the calendar storage system app helps too.

**Comment by S-Sajith** [comment]
Wiping the data of the calendar app worked , thanks !

**Comment by ryan2353** [comment]
I'm having the same problem, I don't see a way to access the system calendar so I use simple calendar pro. Ive tried the above and no change. Is it because I use a third party calendar?

**Comment by ryan2353** [comment]
Switching to etar worked thanks
