### ISSUE TITLE
Feature Request: Human Era calendar

### ISSUE THREAD

**Issue by less-ly** [mvmike/min-cal-widget#154]
Hello mvmike,

The widget is stylish, cool and useful with the neat ability to shift the starting day of the week.

Can you please consider adding a setting to switch to [Human Era](https://en.wikipedia.org//wiki/Holocene_calendar) calendar representation. An indication of the numbering scheme along with the year may come in handy, too.

In short, it's a Gregorian calendar with exactly 10 000 years on top of it, which changes the year only, leaving all the months and dates and days of the week intact. (AD 2023 becomes HE 12023)

Kurzgesagt – In a Nutshell,
a popular science youtube channel, has some nice explanation on why this may be of interest:
[A New History for Humanity – The Human Era](https://www.youtube.com/watch?v=czgOWmtGVGs)

Best regards,
less-ly.

**Comment by mvmike** [comment]
Hi @less-ly,

First time I hear about this concept and loved it, will add some configuration to enable it.

Thanks for the suggestion!

**Comment by mvmike** [comment]
Added under f8209b939dbb0e0ab3bfb6ee17e51c5310fa1557, will be available on [v2.9.0](https://github.com/mvmike/min-cal-widget/releases/tag/v2.9.0)
