### ISSUE TITLE
Build failure on f-droid

### ISSUE THREAD

**Issue by est31** [mvmike/min-cal-widget#16]
Hi, f-droid packager here. Since some time, the build has failed with the gradle error:

```
Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to "8477a8b6e63ed9d62c01bc0b27aa116e9779ff63"
```

I've fixed that error by removing the -beta2 on the `com.android.tools.build:gradle` plugin in the build.gradle file, as you can see in this commit:

https://gitlab.com/fdroid/fdroiddata/commit/6dba094c74c55e5fa3c89c95211c5d703a16c8fc

would be great if you could change the build.gradle accordingly, so that its fixed upstream as well.

Thank you!

**Comment by mvdan** [comment]
This is so weird. These builds were working weeks ago - they were failing at the verification stage, not build stage.

Did Google just break the beta plugins when the final release was out? That's disturbing.

**Comment by est31** [comment]
@mvdan I think its policy that `-beta` versions have an expiry date, to encourage people to use non beta versions, or something like that.

**Comment by est31** [comment]
I've tested at the 0.2.0 version before pushing the commit on my local buildserver so it should work in theory.

**Comment by mvdan** [comment]
Oh, I didn't know that. Then it's definitely a bug in any app using a beta version.

**Comment by est31** [comment]
I've dug up the source code, apparently its 40 days after release of the beta/rc:

https://android.googlesource.com/platform/tools/base/+/7c4f6cf533e9dd36a7aea4ce43ed06ef3b4e5dde/build-system/gradle/src/main/groovy/com/android/build/gradle/BasePlugin.groovy#85

**Comment by mvmike** [comment]
Updated `com.android.tools.build:gradle` plugin as suggested, let me know if it still fails in f-droid CI.

Thanks @est31 and @mvdan!!
