### ISSUE TITLE
"Problem loading widget" FDroid v2.11.1

### ISSUE THREAD

**Issue by sanctimoniousape** [mvmike/min-cal-widget#172]
FDroid v2.10.1 works fine, new 2.11.x versions don't. OnePlus 7 Pro on Android 11.

**Comment by mvmike** [comment]
Hi @sanctimoniousape, this has been already fixed in https://github.com/mvmike/min-cal-widget/issues/170, hopefully f-droid build picks up the new version soon

**Comment by sanctimoniousape** [comment]
It was picked up.  Neither 2.11.0, nor 2.11.1 work for me.

**Comment by mvdan** [comment]
You want https://github.com/mvmike/min-cal-widget/releases/tag/v2.12.2.

**Comment by sanctimoniousape** [comment]
Yes, my apologies - made an assumption I obviously shouldn't have.  Removed FDroid version and installed that one and it works. Thanks for your patience, and sorry for wasting your time.

**Comment by mvmike** [comment]
All good, happy you got it working 🙂
