### ISSUE TITLE
What day is today??

### ISSUE THREAD

**Issue by WoAnerges** [mvmike/min-cal-widget#206]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/mvmike/min-cal-widget/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/mvmike/min-cal-widget/issues) or [closed](https://github.com/mvmike/min-cal-widget/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report could be dismissed otherwise.
- [X] This issue contains only one bug.

### Describe the bug

![Ififif](https://github.com/mvmike/min-cal-widget/assets/1158879/24b59c5d-dd4c-4dbc-949d-01627a28c2fc)
Hey, can you tell what day is today? Stop right there - is useless. You'll never know.

### Steps To Reproduce

 It's literally impossible to tell the current date, if you reduce the widget size. Background transparency: >70%

### Expected Behavior

The text will become all the same, and the current date will blend, looking just like all the other dates 

### Affected app version

2.13.00

### Device

Samsung

### Android version

13

### Launcher

Samsung

### Additional context and screenshots

My suggestion is to add the possibility to CHANGE the current date COLOR, ADD a CIRCLE around it.

By the way, thanks - the widget is great, and this is the only issue that i found 👍👍👍

**Comment by mvmike** [comment]
Hi @WoAnerges, thanks for the contribution.

I'm aware It would be ideal to add some option to better reflect current date, it has also been highlighted in https://github.com/mvmike/min-cal-widget/issues/168

Closing this issue and continuing the conversation there

**Comment by 532910** [comment]
![IMG_20231214_092019.png](https://github.com/mvmike/min-cal-widget/assets/14617699/c78c478b-42a3-4da7-837a-88daf4173fdc)

I'd say it's still hard to say what day is current.
Moreover, underscore looks bad due to assymetry.
