### ISSUE TITLE
current day color looks dark with the last update

### ISSUE THREAD

**Issue by 532910** [mvmike/min-cal-widget#211]
![Screenshot_20231203-183404_crDroid Home.png](https://github.com/mvmike/min-cal-widget/assets/14617699/a857d9bd-f558-4bec-bb98-410f2dfc64e4)

![Screenshot_20231205-145303_crDroid Home.png](https://github.com/mvmike/min-cal-widget/assets/14617699/a305a0e8-e298-4024-a68d-b4cd89304df6)

light red on dark red looks bad

i bet it will not pass wcag contrast recomendations

**Comment by mvmike** [comment]
Fully agree, after seeing it this past weekend had the same impression.

Already started working on other highlight methots although I'm struggling a bit to keep a dynamic background transparency when adding an extra shape (e.g. circle behind the day number or a dash below)

**Comment by mvmike** [comment]
Finally found a way of mixing both the extra shape with a dynamic background 🙂

@532910 what are your thoughts on this beta version with a dash below the number?

My intention is to fix tests and polish other static resources (i.e. screenshots) and do a release before next weekedn

**Comment by mvmike** [comment]
Will be shortening the underline for single digits too

**Comment by mvmike** [comment]
New highlight method available under [v2.15.0](https://github.com/mvmike/min-cal-widget/releases/tag/v2.15.0)
