### ISSUE TITLE
Allow settings screen items to word wrap

### ISSUE THREAD

**Issue by sanctimoniousape** [mvmike/min-cal-widget#229]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/mvmike/min-cal-widget/issues) or [closed](https://github.com/mvmike/min-cal-widget/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the feature request could be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the feature

For people using large fonts due to vision issues (my spouse), and those using smaller or lower-resolution phones like the Unihertz Jelly Star (me), it would be helpful to allow the text descriptions in settings to occupy multiple lines.  See attached example from my phone.

Thanks!

![Screenshot_20240221-121125](https://github.com/mvmike/min-cal-widget/assets/80165446/dec9d640-15f2-4383-91ce-4ad127a5f142)

**Comment by mvmike** [comment]
Hi @sanctimoniousape,

That's a great suggestion! Unfortunately, android does not provide that option out of the box for the `PreferenceScreen`, but I'll see if there is any way of overriding or extending it

**Comment by sanctimoniousape** [comment]
Wow, really?  That's an OS-level limitation?  That kinda blows my mind in this day and age.  I haven't programmed for a couple decades, but it just feels like some things are going just as much backwards as others are going forwards.  Those who don't learn from history, and all that...

Well, thanks for letting me know - I hope you're able to find a way, but even if you're not, I appreciate your willingness to look into it.  Thanks again!

**Comment by mvmike** [comment]
Added in 261cda8d2cd33016efc5daa6c32d73c9fca94531, available from [v2.17.0](https://github.com/mvmike/min-cal-widget/releases/tag/v2.17.0)
