### ISSUE TITLE
There is no the fitst of October 2017

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [mvmike/min-cal-widget#23]
There is no the fitst of October 2017
![img_20171003_024806](https://user-images.githubusercontent.com/14617699/31104392-62208e6e-a7e5-11e7-84fd-dcc6e8b76f10.jpg)

**Comment by mvdan** [comment]
We found the same bug yesterday :)

**Comment by c-e-p-x-u-o** [comment]
I'v found it two days ago, the first of October (:

**Comment by mvmike** [comment]
Saw the same on sunday, @c-e-p-x-u-o , thanks for opening the ticket :)
