### ISSUE TITLE
Show symbol sample in setting

### ISSUE THREAD

**Issue by KrisadaFantasy** [mvmike/min-cal-widget#243]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/mvmike/min-cal-widget/issues) or [closed](https://github.com/mvmike/min-cal-widget/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the feature request could be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the feature

**Summary**: Show symbol sample in the list so user have a clue what's it looks like.

Hello! Thank you so much for this great widget.

Perhaps because English is not my first language for I have no clue what Vertical or Binary is supposed to look like. A few of them in the list as example will save time for user swapping between home screen and setting page to see the result.

I think of something like this;

- Minimal · ∶ ∴
- Vertical · ∶ ⁝
- Circles ◔ ◑ ◕
- Blocks ▁▃▅

**Comment by mvmike** [comment]
That's a nice enhancement!

Would you add it to the selection list and/or in the summary of the current selection?

On top of that, will also include Blocks as a symbol set, it's simple and intuitive 😃

**Comment by KrisadaFantasy** [comment]
Have it in summary is good too! But I think if we have it in the list, even though it will be quite messy, is easier for user as they can see the whole catalogue and make comparison as once.

And yay, Blocks! ▁▃▅😆

**Comment by mvmike** [comment]
Went all in and removed symbol names (what's the point if you can actually see the symbols) in dae51f71cb2a5cb3366b49f193fa23ca334ad2a3 and blocks added in 2b40247822be66f622cd0c431f027e3f0d52aa5c, changes available from [v2.17.0](https://github.com/mvmike/min-cal-widget/releases/tag/v2.17.0)

**Comment by KrisadaFantasy** [comment]
Looks so pretty! But wouldn't no symbol without label at all...too blank? 😂

**Comment by mvmike** [comment]
Thought about it... but also felt weird to show symbols and then a string that says "none", not sure what's better 🙃
