### ISSUE TITLE
Today is the first of July!

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [mvmike/min-cal-widget#26]
![img_20180701_100355](https://user-images.githubusercontent.com/14617699/42131947-5d4cb2b2-7d16-11e8-8f06-cb7d1915d556.jpg)

**Comment by mvmike** [comment]
Could you please verify that you have the latest release, @c-e-p-x-u-o ?

Can't reproduce neither in my personal smartphone nor in the ADV

![image](https://user-images.githubusercontent.com/20406251/42131980-bfbe0854-7d0e-11e8-9255-b6b079a9093a.png)
