### ISSUE TITLE
Should be on F-Droid

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [mvmike/min-cal-widget#27]
Please add it to F-Droid again.

What problems do you have and how can I help you?

**Comment by mvdan** [comment]
We initially added it together as a reproducible build, i.e. reusing upstream's APK signatures.

However, the reproducible build kept breaking at every release - presumably because we weren't always using the same exact versions that the F-Droid buildserver was using, such as the JDK version.

We did twice spend hours figuring out the exact versions we needed to use to follow the version of Debian used by F-Droid. But we sort of gave up after the third time, so I suggested that we simply stop.

The app can of course be added back into F-Droid by anyone, but I don't think upstream or I have any time to spend enough time into reproducible builds.

**Comment by c-e-p-x-u-o** [comment]
created Requests For Packaging
https://gitlab.com/fdroid/rfp/issues/773

**Comment by mvdan** [comment]
Please note that I'm not the author. I simply know him, so I helped him get the app on F-Droid initially. I imagine he's fine with adding it again, though.

**Comment by IzzySoft** [comment]
@mvdan the app was already listed at F-Droid. It was disabled with the comment

> Verifying apks is a pain, temporarily remove until it can be kept up to date

I've checked with the main and the archive repos, no APK there (well, naturally, as the entire app was disabled). So we'd just need to enable it again. The fact that it was already there implicates the author was (at one point) OK with it. And the disabling comment doesn't say that has changed – so we assume that's still the case, shall we? :wink:

**Comment by mvdan** [comment]
Sure. I'm simply clarifying.

**Comment by relan** [comment]
0.3.3 still fails verification, so I re-added MinCal Widget in an "unreproducible" way.

**Comment by mvmike** [comment]
> We initially added it together as a reproducible build, i.e. reusing upstream's APK signatures.
> 
> However, the reproducible build kept breaking at every release - presumably because we weren't always using the same exact versions that the F-Droid buildserver was using, such as the JDK version.
> 
> We did twice spend hours figuring out the exact versions we needed to use to follow the version of Debian used by F-Droid. But we sort of gave up after the third time, so I suggested that we simply stop.
> 
> The app can of course be added back into F-Droid by anyone, but I don't think upstream or I have enough time for reproducible builds.

It was exactly by this, and I'll gladly re-add it to f-droid if there is another way to do so, but not with the `reproducible build` method, it was a complete nightmare

**Comment by IzzySoft** [comment]
@mvdan thanks! That's exactly what relan just triggered (adding it back without reproducible builds, simply "signed by F-Droid"). Sorry that reproducible builds caused nightmares; they would've been great for users switching from other places. But well …

**Comment by mvmike** [comment]
Looks like it's back there → https://f-droid.org/es/packages/cat.mvmike.minimalcalendarwidget/

@relan , is there something that needs to be done for future releases? or they will be added to the f-droid repo automatically?

**Comment by relan** [comment]
> is there something that needs to be done for future releases?

Nope. Just bump versionCode, versionName, tag a new release and F-Droid will pick it up in a couple of days.

**Comment by c-e-p-x-u-o** [comment]
Two strange issues:

    Unable to install with the main "INSTALL" button (on f-droid). Only Versions -> 0.3.3 -> INSTALL works.

    I've uninstalled version from github and installed 0.3.3 version from f-droid. I've give it calendar permission and added new widget but it show "Unable to load widget." After the second reinstall it works fine!

**Comment by relan** [comment]
The APK you downloaded from here is signed by the author, the one from F-Droid---by F-Droid. Android prevents upgrades when signatures differ.

**Comment by c-e-p-x-u-o** [comment]
I have uninstalled author version first.
