### ISSUE TITLE
translation to other languages

### ISSUE THREAD

**Issue by 532910** [mvmike/min-cal-widget#31]
Really I don't need the translation but it may be useful for other users.

I can translate it to russian.

**Comment by mondstern** [comment]
I could translate into German, how could I do that?

**Comment by mvmike** [comment]
Will investigate a bit on how to do it, help will be appreciated :)

**Comment by mvdan** [comment]
I've seen lots of projects using https://weblate.org/en/, and the F-Droid client has been using it for years. Open source, and allows you to import translations as git commits easily.

I'm sure there are other services like it, but this seems like one fairly well optimised for developers.

**Comment by mvmike** [comment]
Have a version working in both English and Catalan that has been internally tested by @mvdan and @zeehio

Already sent the request to `https://hosted.weblate.org/` in order to have a common place to contribute with translations, will keep you updated

**Comment by mvmike** [comment]
Until weblate is up, if you want you can directly attach here a translated copy of the following [resource](https://github.com/mvmike/min-cal-widget/blob/master/app/src/main/res/values/strings.xml) @mondstern @532910

**Comment by 532910** [comment]
Please let us know, when it will be available on https://hosted.weblate.org/.

**Comment by mvmike** [comment]
Sure, will do and update the readme with a badge or something to allow further contributions. As of today, haven't had any answer from them

**Comment by mvmike** [comment]
Weblate just answered, added badge in readme :)

https://hosted.weblate.org/engage/min-cal-widget/?utm_source=widget

**Comment by mondlicht-und-sterne** [comment]
Nice thank you now i can easy translate
