### ISSUE TITLE
no widget

### ISSUE THREAD

**Issue by mondstern** [mvmike/min-cal-widget#32]
the widget can not be placed on the start menu.
my mobile phone:
Sony Xperia XZ2
android 9
Model: H8266

**Comment by mvmike** [comment]
Not able to reproduce from the AVD

Have you tried to place it more than once after installing? Sometimes, because of the runtime permissions, there is some problems the very first time. If so, could you please specify the launcher used?

**Comment by mondstern** [comment]
yes i Have tried to place it more than once after installing. 
launcher used? what you mean with this?

**Comment by ITTech37** [comment]
Same here with Honor View 10 with emui 9 launcher

**Comment by mvdan** [comment]
A "launcher" in Android is what manages the home screen and the widgets on it. Different launchers do certain things differently, so it's possible that a bug with this widget is only reproducible with one launcher.

For example, the steps with screenshots outlined [here](https://www.howtogeek.com/202397/ask-htg-how-do-i-reset-my-android-devices-application-launcher-to-the-default/) show how you can see the current launcher being used on recent Android versions.

What the author is asking is essentially how to reproduce the bug. The widget works for him and me, so we need more information to know what's going wrong on your devices.

**Comment by mondstern** [comment]
i dont have an launcher

**Comment by ITTech37** [comment]
For me, it's the default launcher of Huawei called "Huawei Home".

**Comment by mvmike** [comment]
Unfortunately, can not reproduce the issue in neither a few phones from friends (none of them have android 9, which seems to generate this issue) or a virtual device with your android version.

Could you please provide a logcat to see what's failing, @ITTech37 @mondstern ? If so, we can play a bit with some test version and try to fix it remotely

**Comment by mvmike** [comment]
I understand it might be a bothering procedure if not used to it, but i feel like there is no other way of getting around the problem of not knowing what's failing.

In case you want to try, here you can find a couple of open source projects that would help with it (both in f-droid and google play):

- [Rootless logcat](https://github.com/tananaev/rootless-logcat)
- [LogcatReader](https://github.com/darshanparajuli/LogcatReader)
