### ISSUE TITLE
Bigger letters and numbers optional

### ISSUE THREAD

**Issue by paulle** [mvmike/min-cal-widget#36]
Please add an option for bigger numbed and letters for people with bad eyes or eldery people.

**Comment by mvmike** [comment]
All textSizes are already in `Scale-independent Pixels`, which scale automatically based on the user's device preferences (font size, display size...).

Is there something else that could be done? Tested myself and it scales properly, so it can be seen as good as all other android native texts

**Comment by mvmike** [comment]
Closed due to inactivity. Feel free to reopen it, @paulle, if there is something that can be done regarding accessibility
