### ISSUE TITLE
Wrong monthes localization.

### ISSUE THREAD

**Issue by 532910** [mvmike/min-cal-widget#38]
In linux there are two month properties in `LC_TIME`: `mon` and `alt_mon`.
`mon` is the name of month in nominative case and `alt_mon` is in genitive case.
So `mon` is for 'April 15' form while `alt_mon` is for stanalone month name like just 'April'.

I don't know how this called in android, but min-cal-widget uses `mon` but must use `alt_mon`.

You can't see the difference in english or español, but in russian it's significant.

[Some link about](https://anzwix.com/a/glibc/Implement%20Alternative%20Month%20Names%20(bug%2010871).)

For proper android implementation see https://github.com/SimpleMobileTools/Simple-Calendar.

**Comment by mvmike** [comment]
First of all, thanks for reporting the issue!

Can't open the `anzwix` link, and in `simple-calendar` it looks that they're getting the month string in a similar way of the one used in `mincal` (see the actual line where they're getting the string [here](https://github.com/SimpleMobileTools/Simple-Calendar/blob/master/app/src/main/kotlin/com/simplemobiletools/calendar/pro/helpers/MonthlyCalendarImpl.kt#L119)).

Could you please provide a couple of screenshots with the difference in russian so I can play around and see how to fix it?

**Comment by 532910** [comment]
![IMG_20190315_194150](https://user-images.githubusercontent.com/14617699/54447490-9db4a080-475a-11e9-8fa5-2e6db42800fd.jpg)

**Comment by 532910** [comment]
I've updated anzwix link, but it's not so good as I thought before (:

**Comment by mvmike** [comment]
Created a [new 1.2.2 release](https://github.com/mvmike/min-cal-widget/releases/tag/v1.2.2) with the fix :)

**Comment by 532910** [comment]
It's correct now. Thank you!
