### ISSUE TITLE
%2d formatting

### ISSUE THREAD

**Issue by 532910** [mvmike/min-cal-widget#42]
I'd prefer the day numbers be %2d formatted. What do you think about?

**Comment by mvmike** [comment]
I like them as it is now. Checked also my two linux desktop environment calendars and they're working the same way, as google calendar is doing in web and android versions too. Shall we keep it that way?

**Comment by 532910** [comment]
As I see, all graphical calendars use center-justification. And all text calendars use right-justification.

**Comment by mvmike** [comment]
I'd say that justification can be corrected and stay with the current number of digits, is that ok?

**Comment by 532910** [comment]
Sorry, what do you mean under "number of digits"?  They definitely should not be zero padded.

I mean like cal does:
![image](https://user-images.githubusercontent.com/14617699/56124014-5e0dee00-5f7e-11e9-9235-5b6a91ad7dbe.png)

**Comment by mvmike** [comment]
Agree, thought you were asking for all of them to have to digits, zero-padding those between 1 and 9

**Comment by 532910** [comment]
Sorry for my c (:
```shell
% cat test.c
```
```c
#include <stdio.h>

int main()
{
	printf( "%2d\n", 2 );
	return 0;
}
```
```shell
% gcc -o test ./test.c
% ./test
 2
% 
```
