### ISSUE TITLE
weblate german translation

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [mvmike/min-cal-widget#48]
### german translation on weblate

[](https://hosted.weblate.org/projects/min-cal-widget/min-cal-widget/de/
)https://hosted.weblate.org/projects/min-cal-widget/min-cal-widget/de/

i have translated min-cal-widget into german

**Comment by mvmike** [comment]
transations added in c930c4ce7d619da70b58a298be879e26938da95e, language enabled in 666323dc4ff125527c5441d8061ef0631ba811c5 and the [v1.4.1 release](https://github.com/mvmike/min-cal-widget/releases/tag/v1.4.0) contains the new changes.

Thanks a lot for contributing :)
