### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by milotype** [mvmike/min-cal-widget#55]
Plese update translations from Weblate.

**Comment by milotype** [comment]
Hmmm ... that is strange ... I did **change** the Croatian translation for the string `<a href="https://github.com/mvmike/min-cal-widget">source</a>` 5 hours ago ...

Maybe this kind of changes/issues should be reported to Weblate, in order to show any change in translations (not just uncommited pending ones).

**Comment by mvmike** [comment]
Might be. Meanwhile, if you want it to be updated, feel free to send me the info and i can push it manually :)

**Comment by milotype** [comment]
@mvmike Everything seem to be ok! Sorry ...
