### ISSUE TITLE
month translation is broken

### ISSUE THREAD

**Issue by 532910** [mvmike/min-cal-widget#58]
English (United States):
![image](https://user-images.githubusercontent.com/14617699/101956775-38346300-3c11-11eb-8d1b-3e60fb678d0d.png)

Russia (Russia):
![image](https://user-images.githubusercontent.com/14617699/101956820-497d6f80-3c11-11eb-8fbb-821557ae1928.png)

**Comment by mvmike** [comment]
That's weird, this should be covered by this test: https://github.com/mvmike/min-cal-widget/blob/be6974aab1ec8714fd840c27431e11b24f8b3917/app/src/test/java/cat/mvmike/minimalcalendarwidget/domain/header/MonthYearHeaderServiceTest.java#L103

Could reproduce it, though, will investigate it

**Comment by mvmike** [comment]
Should be fixed after 67907fee14fd79ea7dc0ec8d3726a0a2b9a9684d

Could you please try in the latest release?

**Comment by 532910** [comment]
Works fine with the latest release from F-Droid.
