### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [mvmike/min-cal-widget#59]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by mvmike** [comment]
Moved metadata (screenshots, changelog descriptions and icon) to fastlane in ce59955cd035c6abc40545de32bbca21a3efeb8d

Not sure if we need to remove old metadata from [fdroiddata](https://gitlab.com/fdroid/fdroiddata)

**Comment by fossdd** [comment]
Yes, fdroiddata has also the description. Great that you created fastlane files for these things.

But could you re-tag your release `1.6.0`?

[I see you did not much, which will be added to `1.6.0`.](https://github.com/mvmike/min-cal-widget/compare/v1.6.0...master)

**Comment by mvmike** [comment]
was planning to release a new version soon [with a full migration to kotlin](https://github.com/mvmike/min-cal-widget/compare/master...kotlin-migration)

**Comment by IzzySoft** [comment]
@mvmike any ETA for that so we can mark it in the corresponding MR?

**Comment by mvmike** [comment]
migration is taking longer than expected, just released [v1.6.1](https://github.com/mvmike/min-cal-widget/releases/tag/v1.6.1) based on current master codebase

**Comment by IzzySoft** [comment]
Yeah, things happen… Crossing fingers for easy progress! :crossed_fingers:

So what does that mean for the MR, what note shall we put to keep it easy to follow (and active)?

**Comment by mvmike** [comment]
Screenshots (and all fastlane info) present in fdroid

**Comment by IzzySoft** [comment]
@mvmike not all fastlane info – for that we'd need to remove our local stuff, which is easily done. But before doing so: we've got a load of summaries (`short_description.txt`) for several languages. Would you accept them if we "copied them over" via a PR here, so the work of the translators is not lost?

**Comment by mvmike** [comment]
Hi @IzzySoft , yes it was me who removed them from fdroiddata in [this PR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9003), since the short description has almost no need of being translated.

Maybe in the future we could have fastlane data for all supported languages, but for now i'd say we can get rid of previously existing short descriptions.

Thanks for double checking, though 😃

**Comment by IzzySoft** [comment]
Ah, I see. Problem is that you didn't remove the `Description:` from the YAML, so those summaries were obviously recreated as that indicated we have the metadata locally.

Um, funny: that seems to be fixed now; the YAML was updated yesterday here (and a few days earlier in the fdroiddata repo). In this case apologies for the noise – but yes, it could still have been you'd want those summaries and we could have "rescued" them from history, thanks to git :smile: All good then!
