### ISSUE TITLE
black transparent icon is invisible with dark theme

### ISSUE THREAD

**Issue by 532910** [mvmike/min-cal-widget#63]
Not sure if this is a min-cal-widget issue or f-droid.

![image](https://user-images.githubusercontent.com/14617699/118092419-c38a6e00-b3d4-11eb-8f7e-0094dd918c26.png)

On finger tap:
![image](https://user-images.githubusercontent.com/14617699/118092467-d2712080-b3d4-11eb-9927-fd0d68c26e56.png)

![image](https://user-images.githubusercontent.com/14617699/118092551-ec126800-b3d4-11eb-82aa-0b79fe79a326.png)

**Comment by mvmike** [comment]
Checked with other apps that have a black icon such as [noice](https://f-droid.org/en/packages/com.github.ashutoshgngwr.noice/) and it seems that they add a white background (see its icon [here](https://raw.githubusercontent.com/ashutoshgngwr/noice/master/fastlane/metadata/android/en-US/images/icon.png)).

Problem with mincal is that the background is alpha, so not an f-droid issue and easy to solve on my side, thanks for the report! :)

**Comment by mvmike** [comment]
updated in 3f3c0beb3d417d5a0523f8aa202468c505ebe6bf, let's see how it looks after f-droid picks last fastlane commit

**Comment by mvmike** [comment]
Fixed in both f-droid and gplay

![image](https://user-images.githubusercontent.com/20406251/121141806-a9a94300-c83b-11eb-9db9-bf2914079d6c.png)
![image](https://user-images.githubusercontent.com/20406251/121141687-89798400-c83b-11eb-98f3-614206e55d0a.png)
