### ISSUE TITLE
feature-graphic-google-play

### ISSUE THREAD

**Issue by 532910** [mvmike/min-cal-widget#64]
What about to add Google Play Feature Graphic `assets/feature-graphic-google-play.svg`?

![image](https://user-images.githubusercontent.com/14617699/95226470-a588d980-0805-11eb-8727-02640040787f.png)

![image](https://user-images.githubusercontent.com/14617699/118092764-34318a80-b3d5-11eb-93c1-5afb0d94f5b3.png)

**Comment by mvdan** [comment]
Would be a nice place to show what a widget normally looks like :)

**Comment by mvmike** [comment]
Added in bb40286d4fe7c22a17b253b50259b579d5584e16

**Comment by mvmike** [comment]
Added to both f-droid and gplay

![image](https://user-images.githubusercontent.com/20406251/121141972-d3626a00-c83b-11eb-9b17-3507bf345cee.png)

Thanks a lot @532910 for your improvement suggestions ❤️
