### ISSUE TITLE
in a large widget, write text for the place of icons

### ISSUE THREAD

**Issue by OmlineEditor** [mvmike/min-cal-widget#73]
requesting a new function.
if the widget is stretched and it will be large, then there is a place to write the text what is the event on this day.

for a small widget, only characters without text are available.

![1](https://user-images.githubusercontent.com/13348933/144467715-50c54d43-04ed-4163-b564-6bb459d16907.jpg)

![2](https://user-images.githubusercontent.com/13348933/144467717-31ccb726-f741-4725-ab74-bc98b381a59d.jpg)

**Comment by mvmike** [comment]
Closing as per same considerations of #74

**Comment by OmlineEditor** [comment]
If it is possible to look in the form of text, it is much more convenient than simple characters. please think about it and open a ticket. I hope you can make a very flexible application
