### ISSUE TITLE
the borders of the elements are bolder

### ISSUE THREAD

**Issue by OmlineEditor** [mvmike/min-cal-widget#80]
now it's hard for me to watch the settings, especially during the day in bright light. the elements are all gray and the borders between the elements are poorly separated. I ask you to make the borders more thick and bold

![calend2](https://user-images.githubusercontent.com/13348933/149187479-042a2c68-fea9-4229-ba65-7d3c954ce8cc.png)

**Comment by mvmike** [comment]
Updated the background (cleaner than the border, at least programmatically) here → 8af9d0f6ce9db587bcfb379006caf2c176b467ad
![Screenshot at 2022-01-13 20-42-28](https://user-images.githubusercontent.com/20406251/149398604-9f54f2c6-8f1d-4edd-b8fc-d9ace35ee46a.png)

Will be available on next release.
