### ISSUE TITLE
widget to show only 1 last week

### ISSUE THREAD

**Issue by OmlineEditor** [mvmike/min-cal-widget#83]
at the end of the month there is a lot of useless information on the widget. Many past days. there is very little useful information for the future. I suggest for the widget to show only 1 last week. so more useful information will be

![use](https://user-images.githubusercontent.com/13348933/151397806-61a0129b-a54c-4db9-a67e-b5979d29b59c.jpg)

**Comment by mvmike** [comment]
Added under 1dae198619aeaa9c7e7da3216960c605687519a0, will be available under [v2.5.0](https://github.com/mvmike/min-cal-widget/releases/tag/v2.5.0)
